In [1]:
import requests
import pandas as pd

In [2]:
url = "https://api.github.com/repos/pandas-dev/pandas"

response = requests.get(url)
response

In [3]:
response.json

In [6]:
data = response.json()
type(data)

dict

In [10]:
data.keys()

dict_keys(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url', 'description', 'fork', 'url', 'forks_url', 'keys_url', 'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url', 'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url', 'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url', 'languages_url', 'stargazers_url', 'contributors_url', 'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url', 'comments_url', 'issue_comment_url', 'contents_url', 'compare_url', 'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url', 'milestones_url', 'notifications_url', 'labels_url', 'releases_url', 'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url', 'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size', 'stargazers_count', 'watchers_count', 'language', 'has_issues', 'has_projects', 'has_downloads', 'has_wiki', 'has_pages', 'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled', 'open_issues_count', 'license', 'allow_forking', 'is_template', 'web_commit_signoff_required', 'has_pull_requests', 'pull_request_creation_policy', 'topics', 'visibility', 'forks', 'open_issues', 'watchers', 'default_branch', 'temp_clone_token', 'custom_properties', 'organization', 'network_count', 'subscribers_count'])

In [11]:
repo_info = {
    "name": data["name"],
    "full_name": data["full_name"],
    "stars": data["stargazers_count"],
    "language": data["language"]
}

repo_info

{'name': 'pandas',
 'full_name': 'pandas-dev/pandas',
 'stars': 48827,
 'language': 'Python'}

In [12]:
repo_df = pd.DataFrame([repo_info])
repo_df

     name          full_name  stars language
0  pandas  pandas-dev/pandas  48827   Python

In [14]:
aqi_response = {
    "results": [
        {"station": "Anand Vihar", "pollutant": "PM2.5", "value": 180},
        {"station": "Rohini", "pollutant": "PM2.5", "value": 140},
        {"station": "Dwarka", "pollutant": "PM10", "value": 220}
    ]
}
#sample for understanding
type(aqi_response)

dict

In [15]:

type(aqi_response["results"])

list

In [ ]:
type(aqi_response["results"][0]) #dict
aqi_response["results"][0]

{'station': 'Anand Vihar', 'pollutant': 'PM2.5', 'value': 180}

In [19]:
records = aqi_response["results"]

aqi_df = pd.DataFrame(records)
aqi_df

       station pollutant  value
0  Anand Vihar     PM2.5    180
1       Rohini     PM2.5    140
2       Dwarka      PM10    220

In [21]:
nested_response = {
    "results": [
        {
            "station": "Anand Vihar",
            "pollutant": "PM2.5",
            "value": 180,
            "coordinates": {
                "latitude": 28.6469,
                "longitude": 77.3152
            }
        },
        {
            "station": "Rohini",
            "pollutant": "PM2.5",
            "value": 140,
            "coordinates": {
                "latitude": 28.7383,
                "longitude": 77.0822
            }
        },
        {
            "station": "Dwarka",
            "pollutant": "PM10",
            "value": 220,
            "coordinates": {
                "latitude": 28.5921,
                "longitude": 77.0460
            }
        }
    ]
}
first_record = nested_response["results"][0]
first_record

{'station': 'Anand Vihar',
 'pollutant': 'PM2.5',
 'value': 180,
 'coordinates': {'latitude': 28.6469, 'longitude': 77.3152}}

In [22]:
nested_response["results"]

[{'station': 'Anand Vihar',
  'pollutant': 'PM2.5',
  'value': 180,
  'coordinates': {'latitude': 28.6469, 'longitude': 77.3152}},
 {'station': 'Rohini',
  'pollutant': 'PM2.5',
  'value': 140,
  'coordinates': {'latitude': 28.7383, 'longitude': 77.0822}},
 {'station': 'Dwarka',
  'pollutant': 'PM10',
  'value': 220,
  'coordinates': {'latitude': 28.5921, 'longitude': 77.046}}]

In [23]:
nested_response["results"][1]["coordinates"]["latitude"]

28.7383

In [24]:
rows = []

for record in nested_response["results"]:
    row = {
        "station": record["station"],
        "pollutant": record["pollutant"],
        "value": record["value"],
        "latitude": record["coordinates"]["latitude"],
        "longitude": record["coordinates"]["longitude"]
    }
    rows.append(row)

rows

[{'station': 'Anand Vihar',
  'pollutant': 'PM2.5',
  'value': 180,
  'latitude': 28.6469,
  'longitude': 77.3152},
 {'station': 'Rohini',
  'pollutant': 'PM2.5',
  'value': 140,
  'latitude': 28.7383,
  'longitude': 77.0822},
 {'station': 'Dwarka',
  'pollutant': 'PM10',
  'value': 220,
  'latitude': 28.5921,
  'longitude': 77.046}]

In [25]:
nested_df = pd.DataFrame(rows)
nested_df

       station pollutant  value  latitude  longitude
0  Anand Vihar     PM2.5    180   28.6469    77.3152
1       Rohini     PM2.5    140   28.7383    77.0822
2       Dwarka      PM10    220   28.5921    77.0460

In [26]:
url = "https://api.github.com/search/repositories"

params = {
    "q": "pandas language:python",
    "sort": "stars",
    "order": "desc",
    "per_page": 5
}

response = requests.get(url, params=params)
data = response.json()

In [27]:
data.keys()

dict_keys(['total_count', 'incomplete_results', 'items'])

In [28]:
data["items"][0].keys()

dict_keys(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url', 'description', 'fork', 'url', 'forks_url', 'keys_url', 'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url', 'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url', 'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url', 'languages_url', 'stargazers_url', 'contributors_url', 'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url', 'comments_url', 'issue_comment_url', 'contents_url', 'compare_url', 'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url', 'milestones_url', 'notifications_url', 'labels_url', 'releases_url', 'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url', 'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size', 'stargazers_count', 'watchers_count', 'language', 'has_issues', 'has_projects', 'has_downloads', 'has_wiki', 'has_pages', 'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled', 'open_issues_count', 'license', 'allow_forking', 'is_template', 'web_commit_signoff_required', 'has_pull_requests', 'pull_request_creation_policy', 'topics', 'visibility', 'forks', 'open_issues', 'watchers', 'default_branch', 'score'])

In [29]:
repos = data["items"]

clean_rows = []

for repo in repos:
    row = {
        "name": repo["name"],
        "full_name": repo["full_name"],
        "stars": repo["stargazers_count"],
        "language": repo["language"],
        "url": repo["html_url"]
    }
    clean_rows.append(row)

clean_rows

[{'name': '30-Days-Of-Python',
  'full_name': 'Asabeneh/30-Days-Of-Python',
  'stars': 63015,
  'language': 'Python',
  'url': 'https://github.com/Asabeneh/30-Days-Of-Python'},
 {'name': 'pandas',
  'full_name': 'pandas-dev/pandas',
  'stars': 48827,
  'language': 'Python',
  'url': 'https://github.com/pandas-dev/pandas'},
 {'name': 'tqdm',
  'full_name': 'tqdm/tqdm',
  'stars': 31165,
  'language': 'Python',
  'url': 'https://github.com/tqdm/tqdm'},
 {'name': 'data-science-ipython-notebooks',
  'full_name': 'donnemartin/data-science-ipython-notebooks',
  'stars': 29115,
  'language': 'Python',
  'url': 'https://github.com/donnemartin/data-science-ipython-notebooks'},
 {'name': 'yfinance',
  'full_name': 'ranaroussi/yfinance',
  'stars': 23778,
  'language': 'Python',
  'url': 'https://github.com/ranaroussi/yfinance'}]

In [30]:
repos_df = pd.DataFrame(clean_rows)
repos_df

,name,full_name,stars,language,url
0,30-Days-Of-Python,Asabeneh/30-Days-Of-Python,63015,Python,https://github.com/Asabeneh/30-Days-Of-Python
1,pandas,pandas-dev/pandas,48827,Python,https://github.com/pandas-dev/pandas
2,tqdm,tqdm/tqdm,31165,Python,https://github.com/tqdm/tqdm
3,data-science-ipython-notebooks,donnemartin/data-science-ipython-notebooks,29115,Python,https://github.com/donnemartin/data-science-ip...
4,yfinance,ranaroussi/yfinance,23778,Python,https://github.com/ranaroussi/yfinance