In [1]:
import pandas as pd

In [2]:
aqi_df = pd.read_csv("../data/raw/openaq_delhi_sample.csv")
aqi_df.head()

,location_id,location_name,sensor_id,parameter,value,unit,datetime_utc,datetime_local,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,300.0,µg/m³,2016-11-02T17:30:00Z,2016-11-02T23:00:00+05:30,28.744,77.12
1,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T10:45:00Z,2016-11-03T16:15:00+05:30,28.744,77.12
2,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:00:00Z,2016-11-03T16:30:00+05:30,28.744,77.12
3,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:15:00Z,2016-11-03T16:45:00+05:30,28.744,77.12
4,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:30:00Z,2016-11-03T17:00:00+05:30,28.744,77.12

In [3]:
aqi_df.shape

(1100, 10)

In [4]:
aqi_df.info

<bound method DataFrame.info of       location_id                                 location_name  sensor_id  \
0              13  Delhi Technological University, Delhi - CPCB      13864
1              13  Delhi Technological University, Delhi - CPCB      13864
2              13  Delhi Technological University, Delhi - CPCB      13864
3              13  Delhi Technological University, Delhi - CPCB      13864
4              13  Delhi Technological University, Delhi - CPCB      13864
...           ...                                           ...        ...
1095         2503                        Shadipur, Delhi - CPCB      13860
1096         2503                        Shadipur, Delhi - CPCB      13860
1097         2503                        Shadipur, Delhi - CPCB      13860
1098         2503                        Shadipur, Delhi - CPCB      13860
1099         2503                        Shadipur, Delhi - CPCB      13860

     parameter   value   unit          datetime_utc  \
0         pm25  300.00  µg/m³  2016-11-02T17:30:00Z
1         pm25   93.00  µg/m³  2016-11-03T10:45:00Z
2         pm25   93.00  µg/m³  2016-11-03T11:00:00Z
3         pm25   93.00  µg/m³  2016-11-03T11:15:00Z
4         pm25   93.00  µg/m³  2016-11-03T11:30:00Z
...        ...     ...    ...                   ...
1095      pm25  186.75  µg/m³  2017-02-20T00:00:00Z
1096      pm25  186.75  µg/m³  2017-02-20T00:15:00Z
1097      pm25  186.75  µg/m³  2017-02-20T00:30:00Z
1098      pm25  150.11  µg/m³  2017-02-20T00:45:00Z
1099      pm25  136.78  µg/m³  2017-02-20T01:00:00Z

                 datetime_local  latitude  longitude
0     2016-11-02T23:00:00+05:30   28.7440    77.1200
1     2016-11-03T16:15:00+05:30   28.7440    77.1200
2     2016-11-03T16:30:00+05:30   28.7440    77.1200
3     2016-11-03T16:45:00+05:30   28.7440    77.1200
4     2016-11-03T17:00:00+05:30   28.7440    77.1200
...                         ...       ...        ...
1095  2017-02-20T05:30:00+05:30   28.6517    77.1581
1096  2017-02-20T05:45:00+05:30   28.6517    77.1581
1097  2017-02-20T06:00:00+05:30   28.6517    77.1581
1098  2017-02-20T06:15:00+05:30   28.6517    77.1581
1099  2017-02-20T06:30:00+05:30   28.6517    77.1581

[1100 rows x 10 columns]>

In [5]:
aqi_df.describe()

       location_id     sensor_id        value     latitude    longitude
count  1100.000000  1.100000e+03  1100.000000  1100.000000  1100.000000
mean    353.636364  3.341986e+06   175.087309    28.645789    77.209180
std     691.665352  5.448356e+06   139.743252     0.049430     0.072319
min      13.000000  3.500000e+01    20.600000    28.563262    77.120000
25%      17.000000  3.880000e+02    90.000000    28.623500    77.131023
50%     103.000000  1.386100e+04   132.000000    28.646835    77.186937
75%     236.000000  1.223479e+07   217.000000    28.674045    77.305000
max    2503.000000  1.223561e+07   996.500000    28.744000    77.316032

In [6]:
aqi_df.columns

Index(['location_id', 'location_name', 'sensor_id', 'parameter', 'value',
       'unit', 'datetime_utc', 'datetime_local', 'latitude', 'longitude'],
      dtype='str')

In [8]:
#standardize column names
aqi_df.columns = (
    aqi_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

aqi_df.columns

Index(['location_id', 'location_name', 'sensor_id', 'parameter', 'value',
       'unit', 'datetime_utc', 'datetime_local', 'latitude', 'longitude'],
      dtype='str')

In [10]:
#now we're converting timestamp text into real date time objs to sort and filter easily for later
aqi_df["datetime_utc"] = pd.to_datetime(aqi_df["datetime_utc"])
aqi_df["datetime_local"] = pd.to_datetime(aqi_df["datetime_local"]
                                          )

aqi_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   location_id     1100 non-null   int64
 1   location_name   1100 non-null   str
 2   sensor_id       1100 non-null   int64
 3   parameter       1100 non-null   str
 4   value           1100 non-null   float64
 5   unit            1100 non-null   str
 6   datetime_utc    1100 non-null   datetime64[us, UTC]
 7   datetime_local  1100 non-null   datetime64[us, UTC+05:30]
 8   latitude        1100 non-null   float64
 9   longitude       1100 non-null   float64
dtypes: datetime64[us, UTC+05:30](1), datetime64[us, UTC](1), float64(3), int64(2), str(3)
memory usage: 86.1 KB

In [11]:
#checking pollutant types

aqi_df["parameter"].unique()

<StringArray>
['pm25']
Length: 1, dtype: str

In [14]:
aqi_pm25_df = aqi_df[aqi_df["parameter"] == "pm25"].copy()
aqi_pm25_df.head()
#keeping only pm2.5 data for now, since it's the most commonly used pollutant for AQI calculation and forecasting. We can always add more pollutants later if needed.

,location_id,location_name,sensor_id,parameter,value,unit,datetime_utc,datetime_local,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,300.0,µg/m³,2016-11-02 17:30:00+00:00,2016-11-02 23:00:00+05:30,28.744,77.12
1,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 10:45:00+00:00,2016-11-03 16:15:00+05:30,28.744,77.12
2,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:00:00+00:00,2016-11-03 16:30:00+05:30,28.744,77.12
3,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:15:00+00:00,2016-11-03 16:45:00+05:30,28.744,77.12
4,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:30:00+00:00,2016-11-03 17:00:00+05:30,28.744,77.12

In [16]:
aqi_pm25_df.head()

,location_id,location_name,sensor_id,parameter,value,unit,datetime_utc,datetime_local,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,300.0,µg/m³,2016-11-02 17:30:00+00:00,2016-11-02 23:00:00+05:30,28.744,77.12
1,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 10:45:00+00:00,2016-11-03 16:15:00+05:30,28.744,77.12
2,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:00:00+00:00,2016-11-03 16:30:00+05:30,28.744,77.12
3,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:15:00+00:00,2016-11-03 16:45:00+05:30,28.744,77.12
4,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03 11:30:00+00:00,2016-11-03 17:00:00+05:30,28.744,77.12

In [18]:
aqi_pm25_df = aqi_pm25_df.drop_duplicates()

In [19]:
aqi_pm25_df.shape

(1100, 10)

In [20]:
aqi_pm25_df.isna().sum()

location_id       0
location_name     0
sensor_id         0
parameter         0
value             0
unit              0
datetime_utc      0
datetime_local    0
latitude          0
longitude         0
dtype: int64

In [21]:
aqi_pm25_df[aqi_pm25_df["value"].isna()]

Empty DataFrame
Columns: [location_id, location_name, sensor_id, parameter, value, unit, datetime_utc, datetime_local, latitude, longitude]
Index: []

In [22]:
aqi_pm25_df = aqi_pm25_df.dropna(subset=["value", "datetime_local", "location_name"])

In [ ]:
aqi_pm25_df = aqi_pm25_df[aqi_pm25_df["value"] >= 0]
#removing negative valuesv = cause they're impossible

In [25]:
aqi_pm25_df = aqi_pm25_df.sort_values(["location_name", "datetime_local"])

In [26]:
aqi_pm25_df = aqi_pm25_df.sort_values(["location_name", "datetime_local"])

In [27]:
aqi_pm25_df.to_csv("../data/processed/clean_aqi_pm25.csv", index=False)

In [28]:
clean_check = pd.read_csv("../data/processed/clean_aqi_pm25.csv")
clean_check.head()

,location_id,location_name,sensor_id,parameter,value,unit,datetime_utc,datetime_local,latitude,longitude
0,235,"Anand Vihar, New Delhi - DPCC",384,pm25,132.0,µg/m³,2016-02-05 14:00:00+00:00,2016-02-05 19:30:00+05:30,28.646835,77.316032
1,235,"Anand Vihar, New Delhi - DPCC",384,pm25,322.0,µg/m³,2016-02-06 05:00:00+00:00,2016-02-06 10:30:00+05:30,28.646835,77.316032
2,235,"Anand Vihar, New Delhi - DPCC",384,pm25,188.0,µg/m³,2016-02-06 05:20:00+00:00,2016-02-06 10:50:00+05:30,28.646835,77.316032
3,235,"Anand Vihar, New Delhi - DPCC",384,pm25,188.0,µg/m³,2016-02-06 06:00:00+00:00,2016-02-06 11:30:00+05:30,28.646835,77.316032
4,235,"Anand Vihar, New Delhi - DPCC",384,pm25,170.0,µg/m³,2016-02-06 06:20:00+00:00,2016-02-06 11:50:00+05:30,28.646835,77.316032