In [1]:
import requests
import pandas as pd
import os
from dotenv import load_dotenv

In [2]:
load_dotenv()  # Load environment variables from .env file
OPENAQ_API_KEY = os.getenv("OPENAQ_API_KEY")
OPENAQ_API_KEY is not None

True

In [3]:
url = "https://api.openaq.org/v3/locations"
headers = {
    "X-API-Key": OPENAQ_API_KEY
}
params = {
    "limit": 5
}

response = requests.get(url, headers=headers, params=params)

response.status_code

200

In [7]:
data = response.json()
type(data)
data.keys()

dict_keys(['meta', 'results'])

In [ ]:
len(data["results"])
data["results"][0] #for random location sbtw

{'id': 3,
 'name': 'NMA - Nima',
 'locality': None,
 'timezone': 'Africa/Accra',
 'country': {'id': 152, 'code': 'GH', 'name': 'Ghana'},
 'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
 'provider': {'id': 209, 'name': 'Dr. Raphael E. Arku and Colleagues'},
 'isMobile': False,
 'isMonitor': True,
 'instruments': [{'id': 2, 'name': 'Government Monitor'}],
 'sensors': [{'id': 6,
   'name': 'pm10 µg/m³',
   'parameter': {'id': 1,
    'name': 'pm10',
    'units': 'µg/m³',
    'displayName': 'PM10'}},
  {'id': 5,
   'name': 'pm25 µg/m³',
   'parameter': {'id': 2,
    'name': 'pm25',
    'units': 'µg/m³',
    'displayName': 'PM2.5'}}],
 'coordinates': {'latitude': 5.58389, 'longitude': -0.19968},
 'licenses': None,
 'bounds': [-0.19968, 5.58389, -0.19968, 5.58389],
 'distance': None,
 'datetimeFirst': None,
 'datetimeLast': None}

In [13]:
# getting india's ID first, OpenAQ API has a hierarchical structure, so we need to get the country ID for India first, then use that ID to get the locations within India.
url = "https://api.openaq.org/v3/countries"
headers = {
    "X-API-Key": OPENAQ_API_KEY
}
params = {
    "limit": 100    }

response = requests.get(url, headers=headers, params=params)
countries_data = response.json()
countries_data.keys()

dict_keys(['meta', 'results'])

In [16]:
countries = countries_data["results"]
for country in countries:
    if country["name"] == "India":
       print(country)

{'id': 9, 'code': 'IN', 'name': 'India', 'datetimeFirst': '2016-01-30T00:30:00Z', 'datetimeLast': '2026-05-25T07:30:00Z', 'parameters': [{'id': 1, 'name': 'pm10', 'units': 'µg/m³', 'displayName': None}, {'id': 2, 'name': 'pm25', 'units': 'µg/m³', 'displayName': None}, {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'displayName': None}, {'id': 4, 'name': 'co', 'units': 'µg/m³', 'displayName': None}, {'id': 5, 'name': 'no2', 'units': 'µg/m³', 'displayName': None}, {'id': 6, 'name': 'so2', 'units': 'µg/m³', 'displayName': None}, {'id': 10, 'name': 'o3', 'units': 'ppm', 'displayName': None}, {'id': 15, 'name': 'no2', 'units': 'ppb', 'displayName': None}, {'id': 19, 'name': 'pm1', 'units': 'µg/m³', 'displayName': None}, {'id': 22, 'name': 'wind_direction', 'units': 'deg', 'displayName': None}, {'id': 23, 'name': 'nox', 'units': 'ppb', 'displayName': None}, {'id': 24, 'name': 'no', 'units': 'ppb', 'displayName': None}, {'id': 34, 'name': 'wind_speed', 'units': 'm/s', 'displayName': None}, {'id': 95, 'name': 'pressure', 'units': 'hpa', 'displayName': None}, {'id': 98, 'name': 'relativehumidity', 'units': '%', 'displayName': None}, {'id': 100, 'name': 'temperature', 'units': 'c', 'displayName': None}, {'id': 101, 'name': 'so2', 'units': 'ppb', 'displayName': None}, {'id': 102, 'name': 'co', 'units': 'ppb', 'displayName': None}, {'id': 125, 'name': 'um003', 'units': 'particles/cm³', 'displayName': None}]}

In [ ]:
# now getting india's locations and fidning delhi in them
url = "https://api.openaq.org/v3/locations"
#headers = {
 #   "X-API-Key": OPENAQ_API_KEY
  #  } 
params = {
    "countries_id": "9",
    "limit": 60 }

response = requests.get(url, headers=headers, params=params)
print(response.status_code)
print(response.url)

200
https://api.openaq.org/v3/locations?countries_id=9&limit=40

In [42]:
data = response.json()
locations = data["results"]

In [43]:
for loc in locations:
    print(loc["id"], "-", loc["name"], "-", loc.get("locality"), "-", loc["country"]["name"])

12 - SPARTAN - IIT Kanpur - None - India
13 - Delhi Technological University, Delhi - CPCB - None - India
15 - IGI Airport - None - India
16 - Civil Lines - None - India
17 - R K Puram, Delhi - DPCC - None - India
50 - Punjabi Bagh, Delhi - DPCC - None - India
103 - Income Tax Office, Delhi - CPCB - None - India
235 - Anand Vihar, New Delhi - DPCC - None - India
236 - Mandir Marg, Delhi - DPCC - None - India
286 - Collectorate - Gaya - BSPCB - None - India
301 - Vikas Sadan, Gurugram - HSPCB - None - India
346 - MD University, Rohtak - HSPCB - None - India
354 - Lalbagh, DN Park - None - India
378 - Alandur Bus Depot - None - India
407 - Zoo Park, Hyderabad - TSPCB - None - India
412 - Peenya, Bengaluru - KSPCB - None - India
431 - IHBAS, Delhi - CPCB - None - India
594 - BTM Layout, Bengaluru - KSPCB - None - India
697 - Haldia, Haldia - WBPCB - None - India
703 - Collectorate Jodhpur - RSPCB - None - India
716 - Rabindra Bharati University, Kolkata - WBSPCB - None - India
797 - City Railway Station - KSPCB - None - India
854 - Chandrapur - None - India
860 - Sanjay Palace, Agra - UPPCB - None - India
910 - Victoria Memorial - WBSPCB - None - India
985 - Collectorate - Muzaffarpur - BSPCB - None - India
2345 - VK Industrial Area Jaipur - RSPCB - None - India
2456 - Talkatora District Industries Center, Lucknow - CPCB - None - India
2459 - US Diplomatic Post: Hyderabad - None - India
2460 - US Diplomatic Post: Kolkata - None - India
2461 - US Diplomatic Post: Chennai - None - India
2463 - Central School - None - India
2503 - Shadipur, Delhi - CPCB - None - India
2549 - IIT - None - India
2583 - Sector-6, Panchkula - HSPCB  - None - India
2585 - AAQMS Karve Road Pune - None - India
2586 - Manali, Chennai - CPCB - None - India
2587 - Sector16A, Faridabad - HSPCB - None - India
2589 - SaneguravaHalli - KSPCB - None - India
2591 - Ardhali Bazar - None - India

In [ ]:
# adding all delhi locations to one list
delhi_locations = []

for loc in locations:
    name = loc["name"].lower()
    locality = str(loc.get("locality")).lower()

    if "delhi" in name or "delhi" in locality:
        delhi_locations.append(loc)

len(delhi_locations)

8

In [47]:
# print clearly:
for loc in delhi_locations:
    print(
        loc["id"],
        "-",
        loc["name"],
        "-",
        loc.get("locality"),
        "-",
        loc["coordinates"]
    )

13 - Delhi Technological University, Delhi - CPCB - None - {'latitude': 28.744, 'longitude': 77.12}
17 - R K Puram, Delhi - DPCC - None - {'latitude': 28.563262, 'longitude': 77.186937}
50 - Punjabi Bagh, Delhi - DPCC - None - {'latitude': 28.674045, 'longitude': 77.131023}
103 - Income Tax Office, Delhi - CPCB - None - {'latitude': 28.623499999999996, 'longitude': 77.2494}
235 - Anand Vihar, New Delhi - DPCC - None - {'latitude': 28.646835, 'longitude': 77.316032}
236 - Mandir Marg, Delhi - DPCC - None - {'latitude': 28.6341, 'longitude': 77.2005}
431 - IHBAS, Delhi - CPCB - None - {'latitude': 28.6821, 'longitude': 77.305}
2503 - Shadipur, Delhi - CPCB - None - {'latitude': 28.651699999999998, 'longitude': 77.1581}

In [48]:
# converting to a df
rows = []

for loc in delhi_locations:
    row = {
        "id": loc["id"],
        "name": loc["name"],
        "locality": loc.get("locality"),
        "latitude": loc["coordinates"]["latitude"],
        "longitude": loc["coordinates"]["longitude"]
    }
    rows.append(row)

delhi_locs_df = pd.DataFrame(rows)
delhi_locs_df

,id,name,locality,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",None,28.744000,77.120000
1,17,"R K Puram, Delhi - DPCC",None,28.563262,77.186937
2,50,"Punjabi Bagh, Delhi - DPCC",None,28.674045,77.131023
3,103,"Income Tax Office, Delhi - CPCB",None,28.623500,77.249400
4,235,"Anand Vihar, New Delhi - DPCC",None,28.646835,77.316032
5,236,"Mandir Marg, Delhi - DPCC",None,28.634100,77.200500
6,431,"IHBAS, Delhi - CPCB",None,28.682100,77.305000
7,2503,"Shadipur, Delhi - CPCB",None,28.651700,77.158100

In [51]:
delhi_locs_df.to_csv("../data/raw/openaq_delhi_locs.csv", index=False)

In [55]:
check_df = pd.read_csv("../data/raw/openaq_delhi_locs.csv")
check_df.head(8)

,id,name,locality,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",NaN,28.744000,77.120000
1,17,"R K Puram, Delhi - DPCC",NaN,28.563262,77.186937
2,50,"Punjabi Bagh, Delhi - DPCC",NaN,28.674045,77.131023
3,103,"Income Tax Office, Delhi - CPCB",NaN,28.623500,77.249400
4,235,"Anand Vihar, New Delhi - DPCC",NaN,28.646835,77.316032
5,236,"Mandir Marg, Delhi - DPCC",NaN,28.634100,77.200500
6,431,"IHBAS, Delhi - CPCB",NaN,28.682100,77.305000
7,2503,"Shadipur, Delhi - CPCB",NaN,28.651700,77.158100

In [56]:
for loc in delhi_locations:
    print("\nLOCATION:", loc["id"], "-", loc["name"])
    
    for sensor in loc["sensors"]:
        print(
            "  sensor_id:",
            sensor["id"],
            "| parameter:",
            sensor["parameter"]["name"],
            "| display:",
            sensor["parameter"]["displayName"],
            "| units:",
            sensor["parameter"]["units"]
        )

LOCATION: 13 - Delhi Technological University, Delhi - CPCB
  sensor_id: 13866 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 24 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 13864 | parameter: pm25 | display: PM2.5 | units: µg/m³

LOCATION: 17 - R K Puram, Delhi - DPCC
  sensor_id: 12234782 | parameter: co | display: CO | units: ppb
  sensor_id: 392 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 12234783 | parameter: no | display: NO | units: ppb
  sensor_id: 12234784 | parameter: no2 | display: NO₂ | units: ppb
  sensor_id: 36 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 14340713 | parameter: nox | display: NOX | units: ppb
  sensor_id: 12234785 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 394 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 399 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 12234786 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 35 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 12234787 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 12234788 | parameter: relativehumidity | display: RH | units: %
  sensor_id: 393 | parameter: so2 | display: SO₂ mass | units: µg/m³
  sensor_id: 12234789 | parameter: so2 | display: SO₂ | units: ppb
  sensor_id: 12234790 | parameter: temperature | display: Temperature (C) | units: c
  sensor_id: 14340714 | parameter: wind_direction | display: Wind direction | units: deg
  sensor_id: 14340715 | parameter: wind_speed | display: Wind speed | units: m/s

LOCATION: 50 - Punjabi Bagh, Delhi - DPCC
  sensor_id: 398 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 12234791 | parameter: co | display: CO | units: ppb
  sensor_id: 12234792 | parameter: no | display: NO | units: ppb
  sensor_id: 12234793 | parameter: no2 | display: NO₂ | units: ppb
  sensor_id: 400 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 14340716 | parameter: nox | display: NOX | units: ppb
  sensor_id: 12234794 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 71 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 12234795 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 395 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 396 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 12234796 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 12234797 | parameter: relativehumidity | display: RH | units: %
  sensor_id: 12234798 | parameter: so2 | display: SO₂ | units: ppb
  sensor_id: 397 | parameter: so2 | display: SO₂ mass | units: µg/m³
  sensor_id: 12234799 | parameter: temperature | display: Temperature (C) | units: c
  sensor_id: 14340717 | parameter: wind_direction | display: Wind direction | units: deg
  sensor_id: 14340718 | parameter: wind_speed | display: Wind speed | units: m/s

LOCATION: 103 - Income Tax Office, Delhi - CPCB
  sensor_id: 169 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 13863 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 168 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 13862 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 13861 | parameter: pm25 | display: PM2.5 | units: µg/m³

LOCATION: 235 - Anand Vihar, New Delhi - DPCC
  sensor_id: 12235605 | parameter: co | display: CO | units: ppb
  sensor_id: 385 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 12235606 | parameter: no | display: NO | units: ppb
  sensor_id: 12235607 | parameter: no2 | display: NO₂ | units: ppb
  sensor_id: 382 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 14340864 | parameter: nox | display: NOX | units: ppb
  sensor_id: 380 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 12235608 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 381 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 12235609 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 12235610 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 384 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 12235611 | parameter: relativehumidity | display: RH | units: %
  sensor_id: 12235612 | parameter: so2 | display: SO₂ | units: ppb
  sensor_id: 383 | parameter: so2 | display: SO₂ mass | units: µg/m³
  sensor_id: 12235613 | parameter: temperature | display: Temperature (C) | units: c
  sensor_id: 14340865 | parameter: wind_direction | display: Wind direction | units: deg
  sensor_id: 14340866 | parameter: wind_speed | display: Wind speed | units: m/s

LOCATION: 236 - Mandir Marg, Delhi - DPCC
  sensor_id: 386 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 389 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 390 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 391 | parameter: pm10 | display: PM10 | units: µg/m³
  sensor_id: 388 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 387 | parameter: so2 | display: SO₂ mass | units: µg/m³

LOCATION: 431 - IHBAS, Delhi - CPCB
  sensor_id: 5361 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 747 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 13868 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 13867 | parameter: so2 | display: SO₂ mass | units: µg/m³

LOCATION: 2503 - Shadipur, Delhi - CPCB
  sensor_id: 4851 | parameter: co | display: CO mass | units: µg/m³
  sensor_id: 4852 | parameter: no2 | display: NO₂ mass | units: µg/m³
  sensor_id: 4853 | parameter: o3 | display: O₃ mass | units: µg/m³
  sensor_id: 13860 | parameter: pm25 | display: PM2.5 | units: µg/m³
  sensor_id: 13859 | parameter: so2 | display: SO₂ mass | units: µg/m³

In [57]:
pm25_sensors = []

for loc in delhi_locations:
    for sensor in loc["sensors"]:
        if sensor["parameter"]["name"] == "pm25":
            pm25_sensors.append({
                "location_id": loc["id"],
                "location_name": loc["name"],
                "sensor_id": sensor["id"],
                "parameter": sensor["parameter"]["name"],
                "units": sensor["parameter"]["units"],
                "latitude": loc["coordinates"]["latitude"],
                "longitude": loc["coordinates"]["longitude"]
            })

pm25_sensors

[{'location_id': 13,
  'location_name': 'Delhi Technological University, Delhi - CPCB',
  'sensor_id': 13864,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.744,
  'longitude': 77.12},
 {'location_id': 17,
  'location_name': 'R K Puram, Delhi - DPCC',
  'sensor_id': 35,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.563262,
  'longitude': 77.186937},
 {'location_id': 17,
  'location_name': 'R K Puram, Delhi - DPCC',
  'sensor_id': 12234787,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.563262,
  'longitude': 77.186937},
 {'location_id': 50,
  'location_name': 'Punjabi Bagh, Delhi - DPCC',
  'sensor_id': 396,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.674045,
  'longitude': 77.131023},
 {'location_id': 50,
  'location_name': 'Punjabi Bagh, Delhi - DPCC',
  'sensor_id': 12234796,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.674045,
  'longitude': 77.131023},
 {'location_id': 103,
  'location_name': 'Income Tax Office, Delhi - CPCB',
  'sensor_id': 13861,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.623499999999996,
  'longitude': 77.2494},
 {'location_id': 235,
  'location_name': 'Anand Vihar, New Delhi - DPCC',
  'sensor_id': 12235610,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.646835,
  'longitude': 77.316032},
 {'location_id': 235,
  'location_name': 'Anand Vihar, New Delhi - DPCC',
  'sensor_id': 384,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.646835,
  'longitude': 77.316032},
 {'location_id': 236,
  'location_name': 'Mandir Marg, Delhi - DPCC',
  'sensor_id': 388,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.6341,
  'longitude': 77.2005},
 {'location_id': 431,
  'location_name': 'IHBAS, Delhi - CPCB',
  'sensor_id': 13868,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.6821,
  'longitude': 77.305},
 {'location_id': 2503,
  'location_name': 'Shadipur, Delhi - CPCB',
  'sensor_id': 13860,
  'parameter': 'pm25',
  'units': 'µg/m³',
  'latitude': 28.651699999999998,
  'longitude': 77.1581}]

In [58]:
pm25_sensors_df = pd.DataFrame(pm25_sensors)
pm25_sensors_df

,location_id,location_name,sensor_id,parameter,units,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,µg/m³,28.744000,77.120000
1,17,"R K Puram, Delhi - DPCC",35,pm25,µg/m³,28.563262,77.186937
2,17,"R K Puram, Delhi - DPCC",12234787,pm25,µg/m³,28.563262,77.186937
3,50,"Punjabi Bagh, Delhi - DPCC",396,pm25,µg/m³,28.674045,77.131023
4,50,"Punjabi Bagh, Delhi - DPCC",12234796,pm25,µg/m³,28.674045,77.131023
5,103,"Income Tax Office, Delhi - CPCB",13861,pm25,µg/m³,28.623500,77.249400
6,235,"Anand Vihar, New Delhi - DPCC",12235610,pm25,µg/m³,28.646835,77.316032
7,235,"Anand Vihar, New Delhi - DPCC",384,pm25,µg/m³,28.646835,77.316032
8,236,"Mandir Marg, Delhi - DPCC",388,pm25,µg/m³,28.634100,77.200500
9,431,"IHBAS, Delhi - CPCB",13868,pm25,µg/m³,28.682100,77.305000
10,2503,"Shadipur, Delhi - CPCB",13860,pm25,µg/m³,28.651700,77.158100

In [59]:
sensor_id = pm25_sensors_df.iloc[0]["sensor_id"]
sensor_id

np.int64(13864)

In [60]:
url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"

params = {
    "limit": 100
}

response = requests.get(url, headers=headers, params=params)

print(response.status_code)
print(response.url)

200
https://api.openaq.org/v3/sensors/13864/measurements?limit=100

In [61]:
measurements_data = response.json()

measurements_data.keys()

dict_keys(['meta', 'results'])

In [62]:
measurements = measurements_data["results"]

len(measurements)

100

In [63]:
measurements[0]

{'value': 300.0,
 'flagInfo': {'hasFlags': False},
 'parameter': {'id': 2, 'name': 'pm25', 'units': 'µg/m³', 'displayName': None},
 'period': {'label': 'raw',
  'interval': '01:00:00',
  'datetimeFrom': {'utc': '2016-11-02T17:30:00Z',
   'local': '2016-11-02T23:00:00+05:30'},
  'datetimeTo': {'utc': '2016-11-02T18:30:00Z',
   'local': '2016-11-03T00:00:00+05:30'}},
 'coordinates': None,
 'summary': None,
 'coverage': {'expectedCount': 1,
  'expectedInterval': '01:00:00',
  'observedCount': 1,
  'observedInterval': '00:15:00',
  'percentComplete': 100.0,
  'percentCoverage': 0.0,
  'datetimeFrom': {'utc': '2016-11-02T18:15:00Z',
   'local': '2016-11-02T23:45:00+05:30'},
  'datetimeTo': {'utc': '2016-11-02T18:30:00Z',
   'local': '2016-11-03T00:00:00+05:30'}}}

In [64]:
measurements[0].keys()

dict_keys(['value', 'flagInfo', 'parameter', 'period', 'coordinates', 'summary', 'coverage'])

In [65]:
from pprint import pprint

pprint(measurements[0])

{'coordinates': None,
 'coverage': {'datetimeFrom': {'local': '2016-11-02T23:45:00+05:30',
                               'utc': '2016-11-02T18:15:00Z'},
              'datetimeTo': {'local': '2016-11-03T00:00:00+05:30',
                             'utc': '2016-11-02T18:30:00Z'},
              'expectedCount': 1,
              'expectedInterval': '01:00:00',
              'observedCount': 1,
              'observedInterval': '00:15:00',
              'percentComplete': 100.0,
              'percentCoverage': 0.0},
 'flagInfo': {'hasFlags': False},
 'parameter': {'displayName': None, 'id': 2, 'name': 'pm25', 'units': 'µg/m³'},
 'period': {'datetimeFrom': {'local': '2016-11-02T23:00:00+05:30',
                             'utc': '2016-11-02T17:30:00Z'},
            'datetimeTo': {'local': '2016-11-03T00:00:00+05:30',
                           'utc': '2016-11-02T18:30:00Z'},
            'interval': '01:00:00',
            'label': 'raw'},
 'summary': None,
 'value': 300.0}

In [66]:
measurement_rows = []

for m in measurements:
    row = {
        "sensor_id": sensor_id,
        "value": m["value"],
        "parameter": m["parameter"]["name"],
        "unit": m["parameter"]["units"],
        "datetime_utc": m["period"]["datetimeFrom"]["utc"],
        "datetime_local": m["period"]["datetimeFrom"]["local"]
    }
    measurement_rows.append(row)

measurements_df = pd.DataFrame(measurement_rows)
measurements_df.head()

,sensor_id,value,parameter,unit,datetime_utc,datetime_local
0,13864,300.0,pm25,µg/m³,2016-11-02T17:30:00Z,2016-11-02T23:00:00+05:30
1,13864,93.0,pm25,µg/m³,2016-11-03T10:45:00Z,2016-11-03T16:15:00+05:30
2,13864,93.0,pm25,µg/m³,2016-11-03T11:00:00Z,2016-11-03T16:30:00+05:30
3,13864,93.0,pm25,µg/m³,2016-11-03T11:15:00Z,2016-11-03T16:45:00+05:30
4,13864,93.0,pm25,µg/m³,2016-11-03T11:30:00Z,2016-11-03T17:00:00+05:30

In [67]:
measurements_df.shape

(100, 6)

In [68]:
sensor_info = pm25_sensors_df[pm25_sensors_df["sensor_id"] == sensor_id].iloc[0]

measurements_df["location_id"] = sensor_info["location_id"]
measurements_df["location_name"] = sensor_info["location_name"]
measurements_df["latitude"] = sensor_info["latitude"]
measurements_df["longitude"] = sensor_info["longitude"]

measurements_df.head()

,sensor_id,value,parameter,unit,datetime_utc,datetime_local,location_id,location_name,latitude,longitude
0,13864,300.0,pm25,µg/m³,2016-11-02T17:30:00Z,2016-11-02T23:00:00+05:30,13,"Delhi Technological University, Delhi - CPCB",28.744,77.12
1,13864,93.0,pm25,µg/m³,2016-11-03T10:45:00Z,2016-11-03T16:15:00+05:30,13,"Delhi Technological University, Delhi - CPCB",28.744,77.12
2,13864,93.0,pm25,µg/m³,2016-11-03T11:00:00Z,2016-11-03T16:30:00+05:30,13,"Delhi Technological University, Delhi - CPCB",28.744,77.12
3,13864,93.0,pm25,µg/m³,2016-11-03T11:15:00Z,2016-11-03T16:45:00+05:30,13,"Delhi Technological University, Delhi - CPCB",28.744,77.12
4,13864,93.0,pm25,µg/m³,2016-11-03T11:30:00Z,2016-11-03T17:00:00+05:30,13,"Delhi Technological University, Delhi - CPCB",28.744,77.12

In [69]:
all_measurement_rows = []

for _, sensor_row in pm25_sensors_df.iterrows():
    sensor_id = sensor_row["sensor_id"]

    url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"
    params = {"limit": 100}

    response = requests.get(url, headers=headers, params=params)

    if response.status_code != 200:
        print("Failed:", sensor_id, response.status_code)
        continue

    measurements = response.json()["results"]

    for m in measurements:
        all_measurement_rows.append({
            "location_id": sensor_row["location_id"],
            "location_name": sensor_row["location_name"],
            "sensor_id": sensor_id,
            "parameter": m["parameter"]["name"],
            "value": m["value"],
            "unit": m["parameter"]["units"],
            "datetime_utc": m["period"]["datetimeFrom"]["utc"],
            "datetime_local": m["period"]["datetimeFrom"]["local"],
            "latitude": sensor_row["latitude"],
            "longitude": sensor_row["longitude"]
        })

openaq_df = pd.DataFrame(all_measurement_rows)
openaq_df.head()

,location_id,location_name,sensor_id,parameter,value,unit,datetime_utc,datetime_local,latitude,longitude
0,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,300.0,µg/m³,2016-11-02T17:30:00Z,2016-11-02T23:00:00+05:30,28.744,77.12
1,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T10:45:00Z,2016-11-03T16:15:00+05:30,28.744,77.12
2,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:00:00Z,2016-11-03T16:30:00+05:30,28.744,77.12
3,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:15:00Z,2016-11-03T16:45:00+05:30,28.744,77.12
4,13,"Delhi Technological University, Delhi - CPCB",13864,pm25,93.0,µg/m³,2016-11-03T11:30:00Z,2016-11-03T17:00:00+05:30,28.744,77.12

In [70]:
openaq_df.shape

(1100, 10)

In [71]:
openaq_df.to_csv("../data/raw/openaq_delhi_sample.csv", index=False)

In [72]:
weather_url = "https://api.open-meteo.com/v1/forecast"

weather_params = {
    "latitude": 28.6139,
    "longitude": 77.2090,
    "hourly": "temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,precipitation",
    "timezone": "Asia/Kolkata",
    "forecast_days": 1
}

weather_response = requests.get(weather_url, params=weather_params)

print(weather_response.status_code)
print(weather_response.url)

200
https://api.open-meteo.com/v1/forecast?latitude=28.6139&longitude=77.209&hourly=temperature_2m%2Crelative_humidity_2m%2Cwind_speed_10m%2Cwind_direction_10m%2Cprecipitation&timezone=Asia%2FKolkata&forecast_days=1

In [73]:
weather_data = weather_response.json()
weather_data.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [74]:
hourly = weather_data["hourly"]

weather_df = pd.DataFrame({
    "datetime_local": hourly["time"],
    "temperature_2m": hourly["temperature_2m"],
    "relative_humidity_2m": hourly["relative_humidity_2m"],
    "wind_speed_10m": hourly["wind_speed_10m"],
    "wind_direction_10m": hourly["wind_direction_10m"],
    "precipitation": hourly["precipitation"]
})

weather_df.head()

,datetime_local,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,precipitation
0,2026-05-26T00:00,35.6,20,5.4,354,0.0
1,2026-05-26T01:00,34.4,22,4.2,313,0.0
2,2026-05-26T02:00,33.7,23,5.4,312,0.0
3,2026-05-26T03:00,32.7,24,4.9,324,0.0
4,2026-05-26T04:00,32.0,24,5.1,315,0.0

In [75]:
weather_df.shape

(24, 6)

In [76]:
weather_df.to_csv("../data/raw/openmeteo_delhi_sample.csv", index=False)

In [77]:
pd.read_csv("../data/raw/openmeteo_delhi_sample.csv").head()

,datetime_local,temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,precipitation
0,2026-05-26T00:00,35.6,20,5.4,354,0.0
1,2026-05-26T01:00,34.4,22,4.2,313,0.0
2,2026-05-26T02:00,33.7,23,5.4,312,0.0
3,2026-05-26T03:00,32.7,24,4.9,324,0.0
4,2026-05-26T04:00,32.0,24,5.1,315,0.0