In [2]:
import pandas as pd

In [3]:
data = {
    "station": ["Anand Vihar", "Rohini", "Dwarka"],
    "pollutant": ["PM2.5", "PM2.5", "PM10"],
    "value": [180, 140, 220],
    "timestamp": ["2026-05-20 09:00", "2026-05-20 09:00", "2026-05-20 10:00"]
}
df = pd.DataFrame(data)
df

       station pollutant  value         timestamp
0  Anand Vihar     PM2.5    180  2026-05-20 09:00
1       Rohini     PM2.5    140  2026-05-20 09:00
2       Dwarka      PM10    220  2026-05-20 10:00

In [4]:
df.head()

       station pollutant  value         timestamp
0  Anand Vihar     PM2.5    180  2026-05-20 09:00
1       Rohini     PM2.5    140  2026-05-20 09:00
2       Dwarka      PM10    220  2026-05-20 10:00

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   station    3 non-null      str
 1   pollutant  3 non-null      str
 2   value      3 non-null      int64
 3   timestamp  3 non-null      str
dtypes: int64(1), str(3)
memory usage: 228.0 bytes

In [6]:
df.describe()

       value
count    3.0
mean   180.0
std     40.0
min    140.0
25%    160.0
50%    180.0
75%    200.0
max    220.0

In [7]:
df.shape

(3, 4)

In [8]:
df["station"]

0    Anand Vihar
1         Rohini
2         Dwarka
Name: station, dtype: str

In [9]:
df[["station", "value"]]
df[df["pollutant"] == "PM2.5"]
df[df["value"] > 150]

       station pollutant  value         timestamp
0  Anand Vihar     PM2.5    180  2026-05-20 09:00
2       Dwarka      PM10    220  2026-05-20 10:00

In [10]:
df.to_csv("../data/raw/sample_aqi.csv", index=False)

In [11]:
df_loaded = pd.read_csv("../data/raw/sample_aqi.csv")
df_loaded

       station pollutant  value         timestamp
0  Anand Vihar     PM2.5    180  2026-05-20 09:00
1       Rohini     PM2.5    140  2026-05-20 09:00
2       Dwarka      PM10    220  2026-05-20 10:00